// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43tImbhQU1Fe4sZuiJp0Ae-U_OOw9zzQ',
    appId: '1:194359963045:web:6bdcbca61b4c9503234c4c',
    messagingSenderId: '194359963045',
    projectId: 'syborg-syndicate-workshop',
    authDomain: 'syborg-syndicate-workshop.firebaseapp.com',
    databaseURL: 'https://syborg-syndicate-workshop-default-rtdb.firebaseio.com',
    storageBucket: 'syborg-syndicate-workshop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgPOYpcM_-y3eCaBB2It7j6ImUUxP-aFE',
    appId: '1:194359963045:android:ef267183da1223b4234c4c',
    messagingSenderId: '194359963045',
    projectId: 'syborg-syndicate-workshop',
    databaseURL: 'https://syborg-syndicate-workshop-default-rtdb.firebaseio.com',
    storageBucket: 'syborg-syndicate-workshop.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43tImbhQU1Fe4sZuiJp0Ae-U_OOw9zzQ',
    appId: '1:194359963045:web:18719a1998844d67234c4c',
    messagingSenderId: '194359963045',
    projectId: 'syborg-syndicate-workshop',
    authDomain: 'syborg-syndicate-workshop.firebaseapp.com',
    storageBucket: 'syborg-syndicate-workshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCle6XsAwZ5EsiENSsXV-hWbDzOWqW5Bvg',
    appId: '1:194359963045:ios:71e56942f5cbefd1234c4c',
    messagingSenderId: '194359963045',
    projectId: 'syborg-syndicate-workshop',
    databaseURL: 'https://syborg-syndicate-workshop-default-rtdb.firebaseio.com',
    storageBucket: 'syborg-syndicate-workshop.firebasestorage.app',
    iosBundleId: 'com.syborgcate.workshop',
  );

}